# -*- coding: utf-8 -*-
"""day-71.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h7_bQ4Fs5-uLJPp0wUEIPNsKjSkcmefS
"""

import pandas as pd

df = pd.read_csv('salaries_by_college_major.csv')

df.head()

df.shape

df.columns

df.isna()
#returns tue table with false if value is a number

df.tail()

clean_df = df.dropna()
#dropna returns the data frame without the rows wit NaN
clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max()
clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]
#same as clean_df['Undergraduate Major'][43]

clean_df.loc[43]
#returns the entire row

"""What college major has the highest mid-career salary? How much do graduates with this major earn? (Mid-career is defined as having 10+ years of experience)."""

id = clean_df['Mid-Career 10th Percentile Salary'].idxmax()
print(clean_df.loc[id][0])
clean_df['Mid-Career Median Salary'].max()



print(clean_df['Mid-Career Median Salary'].max())
print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")
clean_df['Undergraduate Major'][8]

"""Which college major has the lowest starting salary and how much do graduates earn after university?"""

print(clean_df['Undergraduate Major'][clean_df['Starting Median Salary'].idxmin()])
clean_df['Starting Median Salary'].min()

"""Which college major has the lowest mid-career salary and how much can people expect to earn with this degree? """

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)

clean_df.head()

id = clean_df['Spread'].idxmin()
clean_df.loc[id]

low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

high_risk = clean_df.sort_values('Spread', ascending=False)
high_risk[['Undergraduate Major', 'Spread']].head()

clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

clean_df.groupby('Group').count()

pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean()
#agrupar por^             ^ e mostra oq

df2 = pd.read_csv('salaries_updated.csv')
df2

table_from_html = pd.read_html("https://www.payscale.com/college-salary-report/majors-that-pay-you-back/bachelors")
df = table_from_html[0].copy()
df.columns = ["Rank", "Major", "Type", "EarlyCareerPay", "MidCareerPay", "HighMeaning"]
df